# Generated by Django 6.0.2 on 2026-02-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_ticket_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, help_text='e.g., bi-music', max_length=50, null=True),
        ),
    ]
