# Generated by Django 6.0.2 on 2026-02-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_category_options_alter_category_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
    ]
