# Generated by Django 6.0.2 on 2026-02-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date_time',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Optional: Leave blank if the event is only a single day/time.', null=True),
        ),
    ]
